### ISSUE TITLE
SSL related NullPonterException

### ISSUE THREAD

**Issue by alexkehayias** [shareablee/http-bolt#1]
Noticed this in the logs. Could be related to SSL issues Facebook was having last night. Not sure why this results in a `NullPointerException`, but we should catch that in the bolt.

```
java.lang.RuntimeException: java.lang.NullPointerException at 
backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) at 
backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) at 
backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) at 
backtype.storm.daemon.executor$fn__3441$fn__3453$fn__3500.invoke(executor.clj:748) at 
backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) at clojure.lang.AFn.run(AFn.java:24) at 
java.lang.Thread.run(Thread.java:701) Caused by: java.lang.NullPointerException at 
sun.security.ssl.JsseJce.isEcAvailable(JsseJce.java:183) at 
sun.security.ssl.CipherSuite$KeyExchange.isAvailable(CipherSuite.java:349) at 
sun.security.ssl.CipherSuite.isAvailable(CipherSuite.java:180) at 
sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(SSLContextImpl.java:337) at 
sun.security.ssl.SSLContextImpl.getDefaultCipherSuiteList(SSLContextImpl.java:295) at 
sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:560) at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:497) at 
sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:73) at 
org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:503) at 
org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:377) at 
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165) at 
org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) at 
org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) at 
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) at 
org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) at 
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) at 
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) at 
clj_http.core$request.invoke(core.clj:283) at clojure.lang.Var.invoke(Var.java:415) at 
clj_http.client$wrap_request_timing$fn__2625.invoke(client.clj:661) at 
clj_http.headers$wrap_header_map$fn__1214.invoke(headers.clj:136) at 
clj_http.client$wrap_query_params$fn__2566.invoke(client.clj:529) at 
clj_http.client$wrap_basic_auth$fn__2572.invoke(client.clj:546) at 
clj_http.client$wrap_oauth$fn__2576.invoke(client.clj:556) at 
clj_http.client$wrap_user_info$fn__2581.invoke(client.clj:569) at 
clj_http.client$wrap_url$fn__2611.invoke(client.clj:627) at 
clj_http.client$wrap_redirects$fn__2432.invoke(client.clj:197) at 
clj_http.client$wrap_decompression$fn__2452.invoke(client.clj:269) at 
clj_http.client$wrap_input_coercion$fn__2519.invoke(client.clj:411) at 
clj_http.client$wrap_additional_header_parsing$fn__2539.invoke(client.clj:460) at 
clj_http.client$wrap_output_coercion$fn__2511.invoke(client.clj:364) at 
clj_http.client$wrap_exceptions$fn__2415.invoke(client.clj:149) at 
clj_http.client$wrap_accept$fn__2548.invoke(client.clj:488) at 
clj_http.client$wrap_accept_encoding$fn__2553.invoke(client.clj:502) at 
clj_http.client$wrap_content_type$fn__2544.invoke(client.clj:478) at 
clj_http.client$wrap_form_params$fn__2591.invoke(client.clj:593) at 
clj_http.client$wrap_nested_params$fn__2608.invoke(client.clj:617) at 
clj_http.client$wrap_method$fn__2586.invoke(client.clj:576) at 
clj_http.cookies$wrap_cookies$fn__127.invoke(cookies.clj:121) at 
clj_http.links$wrap_links$fn__1385.invoke(links.clj:50) at 
clj_http.client$wrap_unknown_host$fn__2615.invoke(client.clj:636) at 
http_bolt.storm$http_bolt__$fn$reify__993$fn__995.invoke(storm.clj:48) at 
http_bolt.storm$capture_time_fn.invoke(storm.clj:21) at 
http_bolt.storm$http_bolt__$fn$reify__993.execute(storm.clj:48) at 
backtype.storm.clojure.ClojureBolt.execute(ClojureBolt.java:83) at
backtype.storm.daemon.executor$fn__3441$tuple_action_fn__3443.invoke(executor.clj:633) at 
backtype.storm.daemon.executor$mk_task_receiver$fn__3364.invoke(executor.clj:401) at 
backtype.storm.disruptor$clojure_handler$reify__1447.onEvent(disruptor.clj:58) at 
backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) ... 6 more
```

**Comment by delaray** [comment]
And it only took 6 years. :-)
